#!/usr/bin/env bash
# fly-migrate-data.sh — copies local store/ into the Fly volume.
#
# This is the "Nikki's memory transplant" step. Copies:
#   - claudeclaw.db          SQLite (memories, conversation_log, FTS5 index, embeddings)
#   - *.json                 BID roster, Plaid items, manual accounts, outreach status
#   - backups/               existing local backups
#
# Skipped:
#   - agent-*.pid            (PIDs from your Mac — meaningless in container)
#   - agent-*-conn.json      (will be regenerated by the new boot)
#   - *.lock                 (better-sqlite3 lockfiles)
#
# Usage:   ./scripts/fly-migrate-data.sh          # incremental rsync, safe to re-run
#          ./scripts/fly-migrate-data.sh --wipe   # wipe remote first (destructive)
#
# Requirements: app must already be deployed once (`fly deploy`) so the
# machine + volume exist and fly ssh works.

set -euo pipefail

PROJECT_ROOT="$(git rev-parse --show-toplevel)"
APP_NAME="claudeclaw-impactworks"
WIPE=false

[[ "${1:-}" == "--wipe" ]] && WIPE=true

cd "$PROJECT_ROOT"

# ── Preflight ─────────────────────────────────────────────────────────────
if [[ ! -d store ]]; then
  echo "❌ store/ not found in $PROJECT_ROOT"
  exit 1
fi

if ! fly status -a "$APP_NAME" >/dev/null 2>&1; then
  echo "❌ App '$APP_NAME' not deployed yet. Run: fly deploy"
  exit 1
fi

LOCAL_DB="store/claudeclaw.db"
if [[ ! -f "$LOCAL_DB" ]]; then
  echo "❌ $LOCAL_DB not found — wrong directory?"
  exit 1
fi

DB_SIZE=$(du -h "$LOCAL_DB" | cut -f1)
echo "📊 Migrating Nikki's memory (${DB_SIZE} SQLite + JSON state) → Fly volume"
echo ""

# ── Stop the Telegram bot temporarily so we don't migrate during a write ──
echo "⏸  Stopping Fly machine briefly to avoid mid-write copy..."
MACHINE_ID=$(fly machines list -a "$APP_NAME" --json | python3 -c 'import json,sys; print(json.load(sys.stdin)[0]["id"])')
fly machines stop "$MACHINE_ID" -a "$APP_NAME"
sleep 3

# ── Optional wipe ─────────────────────────────────────────────────────────
if $WIPE; then
  echo "🗑  Wiping remote /app/store (destructive)..."
  fly ssh console -a "$APP_NAME" --command "rm -rf /app/store/*"
fi

# ── Copy via fly ssh sftp ─────────────────────────────────────────────────
# We use sftp rather than rsync because Fly machines don't always ship with
# rsync installed in the running image (we DO install it in the Dockerfile,
# but the machine is stopped). SFTP works against the stopped volume too.

# Take a quick SQLite checkpoint to make sure the on-disk DB is consistent.
sqlite3 "$LOCAL_DB" "PRAGMA wal_checkpoint(TRUNCATE);" >/dev/null

# Files we DO want to ship
TRANSFER_FILES=(
  "claudeclaw.db"
  "claudeclaw.db-shm"      # may not exist after checkpoint; ignored if missing
  "claudeclaw.db-wal"
  "bid-roster.json"
  "plaid-items.json"
  "manual-accounts.json"
  "manual-transactions.json"
  "outreach-status.json"
)

echo "📤 Uploading state files..."
for f in "${TRANSFER_FILES[@]}"; do
  if [[ -f "store/$f" ]]; then
    echo "   → $f ($(du -h "store/$f" | cut -f1))"
    fly ssh sftp shell -a "$APP_NAME" <<EOF
put store/$f /app/store/$f
EOF
  fi
done

# ── Restart the machine ───────────────────────────────────────────────────
echo "▶️  Starting machine back up..."
fly machines start "$MACHINE_ID" -a "$APP_NAME"

# ── Verify ────────────────────────────────────────────────────────────────
echo ""
echo "⏳ Waiting 8s for boot..."
sleep 8

echo "🔍 Verifying remote state:"
fly ssh console -a "$APP_NAME" --command "ls -lah /app/store/ | head -20"

echo ""
echo "🧠 Memory count check (should match local):"
LOCAL_COUNT=$(sqlite3 "$LOCAL_DB" "SELECT COUNT(*) FROM memories;")
REMOTE_COUNT=$(fly ssh console -a "$APP_NAME" --command "sqlite3 /app/store/claudeclaw.db 'SELECT COUNT(*) FROM memories;'" | tr -d '\r\n ')
echo "   Local:  $LOCAL_COUNT memories"
echo "   Remote: $REMOTE_COUNT memories"

if [[ "$LOCAL_COUNT" == "$REMOTE_COUNT" ]]; then
  echo "✅ Memory transfer verified."
else
  echo "⚠️  Counts differ — investigate before cutover."
  exit 1
fi

echo ""
echo "Next: ./scripts/fly-cutover.sh  (when ready to point DNS at Fly)"
